Earlyus-BeCareful/BeCareful-Server

build.gradle, src/main/java/com/becareful/becarefulserver/domain/sms/controller/SmsController.java, src/main/java/com/becareful/becarefulserver/domain/sms/domain/SmsAuthentication.java, src/main/java/com/becareful/becarefulserver/domain/sms/dto/SmsAuthenticateRequest.java, src/main/java/com/becareful/becarefulserver/domain/sms/dto/SmsSendRequest.java, src/main/java/com/becareful/becarefulserver/domain/sms/repository/SmsRepository.java, src/main/java/com/becareful/becarefulserver/domain/sms/service/SmsService.java, src/main/java/com/becareful/becarefulserver/global/config/RedisConfig.java, src/main/java/com/becareful/becarefulserver/global/config/SecurityConfig.java, src/main/java/com/becareful/becarefulserver/global/constant/SmsConstant.java, src/main/java/com/becareful/becarefulserver/global/exception/ErrorMessage.java, src/main/java/com/becareful/becarefulserver/global/exception/SmsException.java, src/main/java/com/becareful/becarefulserver/global/properties/SmsProperties.java, src/main/java/com/becareful/becarefulserver/global/util/SmsCoolSmsUtil.java, src/main/java/com/becareful/becarefulserver/global/util/SmsSendResult.java, src/main/java/com/becareful/becarefulserver/global/util/SmsTestUtil.java, src/main/java/com/becareful/becarefulserver/global/util/SmsUtil.java, src/main/resources/application-redis.yml, src/main/resources/application-sms.yml, src/main/resources/application.yml, src/test/resources/application-test.yml
=> feat: sms 인증번호 전송 및 인증 API 작성

src/main/java/com/becareful/becarefulserver/domain/caregiver/domain/Caregiver.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/domain/vo/Address.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/dto/request/CaregiverCreateRequest.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/service/CaregiverService.java, src/main/java/com/becareful/becarefulserver/domain/sms/domain/SmsAuthentication.java, src/main/java/com/becareful/becarefulserver/domain/sms/service/SmsService.java, src/main/java/com/becareful/becarefulserver/global/exception/ErrorMessage.java, src/main/java/com/becareful/becarefulserver/global/exception/exception/CaregiverException.java, src/main/java/com/becareful/becarefulserver/global/exception/exception/SmsException.java
=> feat: 주소 필드 생성, 비밀번호 저장, 필수 동의 검증

src/main/java/com/becareful/becarefulserver/domain/auth/controller/AuthController.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/domain/Caregiver.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/dto/request/CaregiverCreateRequest.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/service/CaregiverService.java
=> feat: 요양복지사 생일 필드 추가

src/main/java/com/becareful/becarefulserver/domain/auth/controller/AuthController.java, src/main/java/com/becareful/becarefulserver/domain/auth/service/LoginService.java, src/main/java/com/becareful/becarefulserver/global/config/SwaggerConfig.java
=> fix: swagger cors  에러 해결을 위한 서버 선택 옵션 추가

src/main/java/com/becareful/becarefulserver/domain/caregiver/controller/CaregiverController.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/dto/response/WorkApplicationResponse.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/repository/WorkApplicationWorkLocationRepository.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/service/WorkApplicationService.java, src/main/java/com/becareful/becarefulserver/domain/work_location/domain/WorkLocation.java, src/main/java/com/becareful/becarefulserver/domain/work_location/dto/request/WorkLocationDto.java
=> feat: 일자리 신청 정보 조회 api 작성

src/main/java/com/becareful/becarefulserver/domain/caregiver/controller/CaregiverController.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/domain/WorkApplication.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/service/WorkApplicationService.java, src/main/java/com/becareful/becarefulserver/global/exception/ErrorMessage.java
=> feat: 일자리 신청서 활성화 비활성화 api 구현

src/main/java/com/becareful/becarefulserver/domain/socialworker/controller/NursingInstitutionController.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/controller/SocialworkerController.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/domain/NursingInstitution.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/domain/Socialworker.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/domain/vo/Address.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/domain/vo/Rank.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/dto/request/NursingInstitutionCreateRequest.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/dto/request/SocialworkerCreateRequest.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/dto/response/SocialworkerCreateResponse.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/repository/NursingInstitutionRepository.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/repository/SocialworkerRepository.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/service/NursingInstitutionService.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/service/SocialworkerService.java, src/main/java/com/becareful/becarefulserver/global/config/SecurityConfig.java, src/main/java/com/becareful/becarefulserver/global/exception/ErrorMessage.java, src/main/java/com/becareful/becarefulserver/global/exception/exception/NursingInstitutionException.java, src/main/java/com/becareful/becarefulserver/global/exception/exception/SocialworkerException.java
=> 사회복지사 회원가입 구현

src/main/java/com/becareful/becarefulserver/domain/socialworker/service/NursingInstitutionService.java, src/main/java/com/becareful/becarefulserver/global/config/SecurityConfig.java, src/main/java/com/becareful/becarefulserver/global/constant/SecurityConstant.java, src/main/java/com/becareful/becarefulserver/global/exception/ErrorMessage.java, src/main/java/com/becareful/becarefulserver/global/exception/ErrorResponse.java, src/main/java/com/becareful/becarefulserver/global/exception/GlobalExceptionHandler.java, src/main/java/com/becareful/becarefulserver/global/exception/exception/AuthException.java, src/main/java/com/becareful/becarefulserver/global/exception/exception/CaregiverException.java, src/main/java/com/becareful/becarefulserver/global/exception/exception/DomainException.java, src/main/java/com/becareful/becarefulserver/global/exception/exception/SmsException.java, src/main/java/com/becareful/becarefulserver/global/security/JwtAuthenticationFilter.java, src/main/java/com/becareful/becarefulserver/global/security/JwtExceptionHandlingFilter.java
=> feat: 전역 에러처리 기능 추가

src/main/java/com/becareful/becarefulserver/domain/auth/controller/AuthController.java, src/main/java/com/becareful/becarefulserver/domain/auth/service/LoginService.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/repository/CaregiverRepository.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/service/CaregiverService.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/repository/SocialworkerRepository.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/service/SocialworkerService.java, src/main/java/com/becareful/becarefulserver/global/exception/ErrorMessage.java, src/main/java/com/becareful/becarefulserver/global/exception/exception/SocialworkerException.java
close #33 
** 사회복지사 회원가입 이후 비밀번호 검증 로직 들어갈 예정
=> feat: 사회복지사 로그인 컨트롤러 작성

src/main/java/com/becareful/becarefulserver/domain/caregiver/controller/CaregiverController.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/domain/Career.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/domain/CareerDetail.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/domain/CareerType.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/dto/request/CareerDetailUpdateRequest.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/dto/request/CareerUpdateRequest.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/dto/response/CareerDetailResponse.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/dto/response/CareerResponse.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/repository/CareerDetailRepository.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/repository/CareerRepository.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/service/CareerService.java
=> feat: 경력서 조회, 생성, 수정 API 작성

src/main/java/com/becareful/becarefulserver/domain/caregiver/domain/Caregiver.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/domain/NursingInstitution.java, src/main/java/com/becareful/becarefulserver/global/constant/StaticResourceConstant.java
=> feat: 요양보호사, 기관 엔티티 생성시 기본 프로필 이미지 등록 로직

.gitignore, src/main/java/com/becareful/becarefulserver/domain/caregiver/repository/WorkApplicationWorkLocationRepository.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/controller/RecruitmentController.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/domain/Matching.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/domain/MatchingStatus.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/domain/Recruitment.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/dto/request/RecruitmentCreateRequest.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/repository/MatchingRepository.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/repository/RecruitmentRepository.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/service/RecruitmentService.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/domain/Elderly.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/repository/ElderlyRepository.java, src/main/java/com/becareful/becarefulserver/global/exception/ErrorMessage.java, src/main/java/com/becareful/becarefulserver/global/exception/exception/NursingInstitutionException.java, src/main/java/com/becareful/becarefulserver/global/exception/exception/RecruitmentException.java, src/main/java/com/becareful/becarefulserver/global/util/AuthUtil.java
=> feat: 매칭 공고 등록 API

src/main/java/com/becareful/becarefulserver/domain/caregiver/dto/response/WorkScheduleResponse.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/controller/RecruitmentController.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/domain/RecruitmentTag.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/dto/response/RecruitmentResponse.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/repository/MatchingRepository.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/service/RecruitmentService.java, src/main/java/com/becareful/becarefulserver/global/exception/ErrorMessage.java
=> feat: 요양보호사 일자리 공고 리스트 조회 API

src/main/java/com/becareful/becarefulserver/domain/recruitment/controller/RecruitmentController.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/domain/RecruitmentTag.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/dto/response/ElderlyInfoResponse.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/dto/response/InstitutionInfoResponse.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/dto/response/RecruitmentDetailResponse.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/dto/response/RecruitmentInfoResponse.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/dto/response/RecruitmentResponse.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/service/RecruitmentService.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/domain/Elderly.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/domain/vo/Address.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/domain/vo/ResidentialAddress.java, src/main/java/com/becareful/becarefulserver/global/exception/ErrorMessage.java
close #18 
어르신 등록 API 완성 이후 데이터 넣어서 조회 테스트 하고 머지 예정
=> feat: 요양보호사 일자리 공고 상세 조회 API 작성

src/main/java/com/becareful/becarefulserver/domain/caregiver/domain/converter/DayOfWeekSetConverter.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/controller/RecruitmentController.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/domain/Matching.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/domain/MediationType.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/domain/converter/MediationTypeSetConverter.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/dto/request/RecruitmentMediateRequest.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/service/RecruitmentService.java
=> feat: 일자리 조율 지원 API 작성

src/main/java/com/becareful/becarefulserver/domain/caregiver/domain/CareerDetail.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/dto/request/CareerDetailUpdateRequest.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/dto/response/CareerDetailResponse.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/dto/response/CaregiverHomeResponse.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/dto/response/CaregiverMyPageHomeResponse.java
- 마이페이지 홈화면 성별 응답 추가
- 경력서 상세 경력의 근무 경력 문자열로 주고 받기
- 홈 화면 데이터에 isWorking 필드 추가
=> fix: 프론트 요청에 따른 응답 데이터 형식 수정

build.gradle, src/main/java/com/becareful/becarefulserver/domain/auth/service/LoginService.java, src/main/java/com/becareful/becarefulserver/domain/community/controller/PostController.java, src/main/java/com/becareful/becarefulserver/domain/community/domain/Comment.java, src/main/java/com/becareful/becarefulserver/domain/community/domain/Post.java, src/main/java/com/becareful/becarefulserver/domain/community/domain/PostBoard.java, src/main/java/com/becareful/becarefulserver/domain/community/dto/request/PostCreateRequest.java, src/main/java/com/becareful/becarefulserver/domain/community/dto/request/PostUpdateRequest.java, src/main/java/com/becareful/becarefulserver/domain/community/service/PostService.java, src/main/java/com/becareful/becarefulserver/domain/recruitment/service/RecruitmentService.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/domain/SocialWorker.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/dto/response/SocialWorkerHomeResponse.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/repository/SocialworkerRepository.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/service/ElderlyService.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/service/NursingInstitutionService.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/service/SocialworkerService.java, src/main/java/com/becareful/becarefulserver/global/exception/ErrorMessage.java, src/main/java/com/becareful/becarefulserver/global/exception/exception/PostBoardException.java, src/main/java/com/becareful/becarefulserver/global/exception/exception/PostException.java, src/main/java/com/becareful/becarefulserver/global/util/AuthUtil.java, src/main/resources/application.yml, src/test/java/com/becareful/becarefulserver/common/DatabaseCleaner.java, src/test/java/com/becareful/becarefulserver/common/IntegrationTest.java, src/test/java/com/becareful/becarefulserver/common/SocialWorkerSecurityContextFactory.java, src/test/java/com/becareful/becarefulserver/common/WithSocialWorker.java, src/test/java/com/becareful/becarefulserver/community/api/PostIntegrationTest.java, src/test/java/com/becareful/becarefulserver/fixture/NursingInstitutionFixture.java, src/test/java/com/becareful/becarefulserver/fixture/SocialWorkerFixture.java
close #106 
- 이미지 업로드, 파일 업로드 기능은 추후에 추가적으로 개발할 예정
=> feat: 게시글 작성/수정/삭제 API 생성

src/main/java/com/becareful/becarefulserver/domain/caregiver/controller/CaregiverController.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/controller/WorkApplicationController.java, src/main/java/com/becareful/becarefulserver/domain/matching/controller/CompletedMatchingController.java, src/main/java/com/becareful/becarefulserver/domain/matching/controller/ContractController.java, src/main/java/com/becareful/becarefulserver/domain/matching/controller/RecruitmentController.java, src/main/java/com/becareful/becarefulserver/domain/matching/controller/SocialWorkerRecruitmentController.java, src/main/java/com/becareful/becarefulserver/domain/sms/controller/SmsController.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/controller/ElderlyController.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/controller/NursingInstitutionController.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/controller/SocialWorkerController.java
- api url 부자연스러운 경우 수정
- recruitment 컨트롤러 분리
- caregiver 컨트롤러 분리
=> refactor: 컨트롤러 정리

src/main/java/com/becareful/becarefulserver/domain/association/domain/Association.java, src/main/java/com/becareful/becarefulserver/domain/association/dto/response/AssociationMyResponse.java, src/main/java/com/becareful/becarefulserver/domain/association/service/AssociationService.java, src/main/java/com/becareful/becarefulserver/domain/community/controller/CommunityController.java, src/main/java/com/becareful/becarefulserver/domain/community/dto/response/AssociationInfoResponse.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/repository/SocialWorkerRepository.java
=> feat: 로그인한 사용자의 협회 정보 조회 API 작성

src/main/java/com/becareful/becarefulserver/domain/association/controller/AssociationController.java, src/main/java/com/becareful/becarefulserver/domain/association/service/AssociationService.java
close #145 
- 협회 생성시 4개의 게시판을 함께 생성하는 로직을 추가하였습니다.
=> feat: 협회 생성시 게시판 생성 로직 작성

src/main/java/com/becareful/becarefulserver/domain/socialworker/controller/ElderlyController.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/service/ElderlyService.java, src/main/java/com/becareful/becarefulserver/global/exception/ErrorMessage.java
이미지 업로드시 기관 번호는 필요하지 않아 제거하였습니다.
이미지 이름 생성시 기관 번호 대신 api 요청 시간 (나노초까지) 을 기준으로 생성하도록 하였습니다.
=> fix: 이미지 업로드시 불필요 파라미터 삭제

src/main/java/com/becareful/becarefulserver/domain/caregiver/domain/WorkApplication.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/domain/WorkSalaryType.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/domain/WorkSalaryUnitType.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/dto/request/WorkApplicationUpdateRequest.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/dto/response/WorkApplicationResponse.java, src/main/java/com/becareful/becarefulserver/domain/matching/domain/Contract.java, src/main/java/com/becareful/becarefulserver/domain/matching/domain/Recruitment.java, src/main/java/com/becareful/becarefulserver/domain/matching/dto/RecruitmentDto.java, src/main/java/com/becareful/becarefulserver/domain/matching/dto/request/ContractEditRequest.java, src/main/java/com/becareful/becarefulserver/domain/matching/dto/request/RecruitmentCreateRequest.java, src/main/java/com/becareful/becarefulserver/domain/matching/service/ContractService.java
- '일급' 타입 추가
- @Enumerated 어노테이션 추가
- WorkSalaryType -> WorkSalaryUnitType 으로 더 명확하게 클래스명 변경
close #197
=> fix: '일급' 타입 추가

src/main/java/com/becareful/becarefulserver/global/config/SecurityConfig.java, src/main/java/com/becareful/becarefulserver/global/config/SwaggerConfig.java, src/main/java/com/becareful/becarefulserver/global/constant/UrlConstant.java
=> fix: 스웨거 서버주소 및 CORS 설정 변경

src/main/java/com/becareful/becarefulserver/domain/chat/dto/response/ChatroomContentResponse.java, src/main/java/com/becareful/becarefulserver/domain/matching/dto/InstitutionSimpleDto.java, src/main/java/com/becareful/becarefulserver/domain/matching/dto/RecruitmentDto.java, src/main/java/com/becareful/becarefulserver/domain/matching/dto/RecruitmentSimpleDto.java, src/main/java/com/becareful/becarefulserver/domain/matching/dto/response/RecruitmentDetailResponse.java
close #273 
채팅 상세 응답 형식에 기관 이미지 추가
요양보호사 정보도 simple dto 로 응답하도록 수정
=> refactor: 채팅 상세 데이터 응답 형식 리팩토링

src/main/java/com/becareful/becarefulserver/domain/chat/dto/ContractDto.java
=> feat: 계약서 데이터에 생성 시각 추가

src/main/java/com/becareful/becarefulserver/domain/chat/dto/response/ChatroomContentResponse.java
=> refactor: 채팅방 데이터 내에 recruitment id 추가

src/main/java/com/becareful/becarefulserver/domain/community/dto/PostSimpleDto.java
=> feat: 썸네일 url 응답하도록 추가

src/main/java/com/becareful/becarefulserver/domain/community/dto/response/CommentResponse.java
=> feat: 커뮤니티 게시글 댓글 response 수정

.github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/fix.md, .github/ISSUE_TEMPLATE/refactor.md
=> chore: 이슈 템플릿 양식 수정

src/main/java/com/becareful/becarefulserver/domain/socialworker/controller/ElderlyController.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/domain/Elderly.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/dto/request/ElderlyUpdateRequest.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/service/ElderlyService.java
- 어르신 정보 수정 API 로직 개선
close #361
=> refactor: 어르신 업데이트 로직 리팩토링

src/main/java/com/becareful/becarefulserver/domain/caregiver/service/CaregiverService.java, src/main/java/com/becareful/becarefulserver/domain/caregiver/service/WorkApplicationService.java, src/main/java/com/becareful/becarefulserver/domain/chat/service/CaregiverChatService.java, src/main/java/com/becareful/becarefulserver/domain/matching/controller/CaregiverMatchingController.java, src/main/java/com/becareful/becarefulserver/domain/matching/domain/Matching.java, src/main/java/com/becareful/becarefulserver/domain/matching/domain/MatchingStatus.java, src/main/java/com/becareful/becarefulserver/domain/matching/dto/response/CaregiverAppliedRecruitmentsResponse.java, src/main/java/com/becareful/becarefulserver/domain/matching/repository/CompletedMatchingRepository.java, src/main/java/com/becareful/becarefulserver/domain/matching/repository/MatchingRepository.java, src/main/java/com/becareful/becarefulserver/domain/matching/service/CaregiverMatchingService.java, src/main/java/com/becareful/becarefulserver/domain/matching/service/SocialWorkerMatchingService.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/dto/response/SocialWorkerHomeResponse.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/service/SocialWorkerService.java
- 매칭된 요양보호사 숫자 데이터 추가
- 매칭 통계를 공고 통계로 변경
- 매칭 상태 enum  이름을 MatchingStatus 로 변경
close #363
=> refactor: 사회복지사 홈 화면 리팩토링

src/main/java/com/becareful/becarefulserver/domain/caregiver/service/WorkApplicationService.java, src/main/java/com/becareful/becarefulserver/domain/matching/domain/Recruitment.java, src/main/java/com/becareful/becarefulserver/domain/matching/domain/RecruitmentStatus.java, src/main/java/com/becareful/becarefulserver/domain/matching/dto/RecruitmentDto.java, src/main/java/com/becareful/becarefulserver/domain/matching/dto/RecruitmentSimpleDto.java, src/main/java/com/becareful/becarefulserver/domain/matching/service/SocialWorkerMatchingService.java, src/main/java/com/becareful/becarefulserver/domain/socialworker/service/SocialWorkerService.java, src/main/java/com/becareful/becarefulserver/global/exception/ErrorMessage.java
공고 상태 (recruitment status) 추가 및 리팩토링
close #366
=> refactor: recruitment status 추가
